/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ARK (https://sketchfab.com/arkvn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chibi-astronaut-8e16849ed0ab411098057697c2ecb587
Title: Chibi Astronaut
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import * as THREE from 'three'

// Define the structure of your GLTF scene nodes and materials
type ChibiAstronautNodes = {
  GLTF_created_0_rootJoint: THREE.Bone
  Object_7: THREE.SkinnedMesh
  Object_8: THREE.SkinnedMesh
  Object_9: THREE.SkinnedMesh
  Object_10: THREE.SkinnedMesh
  Object_11: THREE.SkinnedMesh
  Object_12: THREE.SkinnedMesh
  Object_13: THREE.SkinnedMesh
  Object_14: THREE.SkinnedMesh
  Object_15: THREE.SkinnedMesh
  Object_16: THREE.SkinnedMesh
  Object_18: THREE.SkinnedMesh
  Object_19: THREE.SkinnedMesh
  Object_20: THREE.SkinnedMesh
  Object_21: THREE.SkinnedMesh
  Object_51: THREE.Mesh
  Object_53: THREE.Mesh
  Object_55: THREE.Mesh
}

type ChibiAstronautMaterials = {
  'Cloth.001': THREE.Material
  'Cloth.002': THREE.Material
  Hand: THREE.Material
  Metal: THREE.Material
  Head: THREE.Material
  'Backpack.001': THREE.Material
  'Backpack.002': THREE.Material
  IDK2: THREE.Material
  Light: THREE.Material
  Outline: THREE.Material
  material: THREE.Material
  Class: THREE.Material
  Planet: THREE.Material
  Planet_Ring: THREE.Material
}

// Define props interface
interface ModelProps extends JSX.IntrinsicElements {}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  
  // Type assertions for specific nodes and materials we know exist
  const typedNodes = nodes as ChibiAstronautNodes & typeof nodes
  const typedMaterials = materials as ChibiAstronautMaterials & typeof materials
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.921, 0, 0]}>
            <primitive object={typedNodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={typedNodes.Object_7.geometry}
              material={typedMaterials['Cloth.001']}
              skeleton={typedNodes.Object_7.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_8.geometry}
              material={typedMaterials['Cloth.002']}
              skeleton={typedNodes.Object_8.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_9.geometry}
              material={typedMaterials.Hand}
              skeleton={typedNodes.Object_9.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_10.geometry}
              material={typedMaterials.Metal}
              skeleton={typedNodes.Object_10.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_11.geometry}
              material={typedMaterials.Head}
              skeleton={typedNodes.Object_11.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_12.geometry}
              material={typedMaterials['Backpack.001']}
              skeleton={typedNodes.Object_12.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_13.geometry}
              material={typedMaterials['Backpack.002']}
              skeleton={typedNodes.Object_13.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_14.geometry}
              material={typedMaterials.IDK2}
              skeleton={typedNodes.Object_14.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_15.geometry}
              material={typedMaterials.Light}
              skeleton={typedNodes.Object_15.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_16.geometry}
              material={typedMaterials.Outline}
              skeleton={typedNodes.Object_16.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_18.geometry}
              material={typedMaterials.Head}
              skeleton={typedNodes.Object_18.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_19.geometry}
              material={typedMaterials.material}
              skeleton={typedNodes.Object_19.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_20.geometry}
              material={typedMaterials.Class}
              skeleton={typedNodes.Object_20.skeleton}
            />
            <skinnedMesh
              geometry={typedNodes.Object_21.geometry}
              material={typedMaterials.Outline}
              skeleton={typedNodes.Object_21.skeleton}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={typedNodes.Object_51.geometry}
            material={typedMaterials.Planet}
            position={[-2.726, 0.124, 0.003]}
            rotation={[2.652, 1.506, -2.954]}
            scale={0.686}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={typedNodes.Object_53.geometry}
            material={typedMaterials.Planet_Ring}
            position={[-2.726, 0.137, -0.001]}
            rotation={[1.948, 1.528, -2.288]}
            scale={[0.981, 0.3, 0.981]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={typedNodes.Object_55.geometry}
            material={typedMaterials.Planet_Ring}
            position={[-2.726, 0.137, -0.001]}
            rotation={[2.484, 1.498, -2.782]}
            scale={[1.409, 0.3, 1.409]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')