'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ThreeD from "./ThreeD";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased realatve w-screen h-screen overflow-hidden`}
      >
        <nav className="sticky top-0 left-0 z-10">
          <Navbar />
        </nav>
        {children}
        <div className="w-full h-full absolute top-0">
          <ThreeD />
                </div>

      </body>
    </html>
  );
}
